### ISSUE TITLE
Hang caused by mp3

### ISSUE THREAD

**Issue by jai-x** [mcnutty26/music-get#14] opened 2016-03-05 04:16 UTC
At 2016/03/05 4:03 am the music server became unresponsive in playback. The music server was able to correctly serve both the admin page and the regular index page during this issue. The music server would not correctly kill the currently "non-playing" song via the web API or via key command. The music server had to be restarted by stopping the program via command line using Ctrl-C. The file that caused the incident was [this mp3 file](http://puu.sh/nvgGx/62dbe3f84f.mp3).This may or may not have been a random occurrence.

**Comment by mcnutty26** [comment] 2016-03-05 18:50
Looks like the problem is that timeout hangs (probably due to some of the flags passed to mplayer?). Gonna look into it and see how we can prevent it. It's possibly a bug in timeout or mplayer.

EDIT: Looks like the problem only occurs when calling timout _from java_. Queueing the song to music-get on my laptop causes it to crash, but music-get recovers. The version of mplayer on the music server was released in 2012, which may have something to do with it.

**Comment by mcnutty26** [comment] 2016-03-05 21:10
Given that the problem seemed to be with mplayer not responding, I've pushed a fix in 43b4124e572fb35bbd8b4136b3eef4d49aec57f2 which should have java carry on if mplayer hangs for whatever reason. I'll deploy it tomorrow and close this if it works.

**Comment by mcnutty26** [comment] 2016-03-06 11:37
Closing as update tested today, and killing seems to work (possible interference by #15 perhaps?)

**Closed as completed by mcnutty26** 2016-03-06 11:37 UTC
Labels: bug
